### PR TITLE
Add support for cloaked messages

### PR DESCRIPTION
**Pull request by Powersource**
Fixes https://github.com/ssbc/ssb-uri2/issues/13

### CODE REVIEW

**Comment by Powersource** [comment]
@staltz @mixmix

**Review by staltz — CHANGES_REQUESTED** [review]
Is it possible to revert the code style changes? :grimacing:

**Comment by Powersource** [comment]
Sure. It is applied by Prettier though fwiw. But weird that it didn't run it on src/index.ts. Maybe because the test files are js

**Comment by staltz** [comment]
Alternatively, you can copy the prettier settings and scripts from here https://github.com/ssbc/ssb-threads which *should* work on typescript.

**Review by staltz — CHANGES_REQUESTED** [review]
Thanks for the prettier. One last request: perhaps a test for the new cloaked URI? Add a fixture for it and test it in happy.js

**Comment by Powersource** [comment]
There is a new test in happy though? Or you want a different one?

**Review by staltz — APPROVED** [review]
Oh, there was a test! Sorry for that, I think my GitHub was showing an outdated git diff (it still had some code style changes in tests)

**Comment by staltz** [comment]
2.3.0 released

**Pull request merged**
